# Generated by Django 6.0.2 on 2026-03-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('lv_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_leave', models.IntegerField(db_column='no of leave')),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
