# Generated by Django 6.0.2 on 2026-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='no_of_leave',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
