# Generated by Django 6.0.2 on 2026-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0002_leave_date_alter_leave_no_of_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(),
        ),
    ]
