# Generated by Django 6.0.2 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholar_id', models.AutoField(primary_key=True, serialize=False)),
                ('scholarship', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
                ('sc_status', models.CharField(max_length=45)),
                ('atype', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'scholarship',
            },
        ),
    ]
