# Generated by Django 6.0.2 on 2026-03-19 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
        ('teacher', '0002_alter_teacher_options_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='end_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='details',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='atype',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='sc_status',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='scholar_id',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='status',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_grade',
            field=models.IntegerField(default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_grade',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AlterModelTable(
            name='scholarship',
            table=None,
        ),
    ]
