# Generated by Django 6.0.2 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
            ],
        ),
    ]
