# Generated by Django 6.0.2 on 2026-03-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'work',
            },
        ),
    ]
