# Generated by Django 6.0.2 on 2026-03-18 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='work',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='teach',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(default='Untitled Work', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
