# Generated by Django 6.0.2 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubactivity',
            fields=[
                ('clb_id', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clubactivity',
                'managed': False,
            },
        ),
    ]
