# Generated by Django 6.0.2 on 2026-03-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubactivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubactivity',
            options={},
        ),
    ]
