# Generated by Django 6.0.2 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('division', models.CharField(max_length=45)),
                ('timetable', models.CharField(max_length=450)),
            ],
            options={
                'db_table': 'timetable',
                'managed': False,
            },
        ),
    ]
