# Generated by Django 6.0.2 on 2026-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_field', models.CharField(db_column='from', max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'transportation',
            },
        ),
    ]
