# Generated by Django 6.0.2 on 2026-03-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='att_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='te',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='st',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student.student'),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table=None,
        ),
    ]
